# MAIN base
baseURL = "https://apsho-hugo.netlify.app/"
languageCode = "en-us"
title = "BeeData | Nắm bắt cơ hội, tạo ra giá trị"
theme = "apsho-hugo-theme"

# Navigation Bar
[[menu.main]]
    name = "Trang chủ"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "Về chúng tôi"
    url = "#feature"
    weight = 2
# [[menu.main]]
#     name = "Dịch Vụ"
#     url = "#faq"
#     weight = 3
[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Trang chủ"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Bài viết mới"
    url = "/blog"
    weight = 2
[[menu.sitemap]]
    name = "English"
    url = "#"
    weight = 3
[[menu.sitemap]]
    name = "Liên hệ"
    url = "/contact"
    weight = 4

# Footer Address
[params.address]
address = "Singapore"
email = "hello@beedatasolutions.com"
phone = "+(65) 90537440"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/beedatasolutions"
twitter = "#"
github = "#"

[params]

# Header
logo = "images/logo.png"
fabFormURL = "https://fabform.io/f/jveULm5"
googleAnalytics = "UA-175025671-2"

# Footer
footerTitle = "Tìm hiểu thêm về dịch vụ tư vấn"
copyright1 = "All right reserved"
copyright2 = "Copyright ©  <a href=\"https://beedatasolutions.com\" target=\"_blank\">BeeData Solutions </a> {year}"

#contact
email = "help@staticmania.com"
